// <auto-generated />
using System;
using EmployeesApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeesApi.Migrations
{
    [DbContext(typeof(EmployeesDbContext))]
    [Migration("20181009160029_Migration1")]
    partial class Migration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmployeesApi.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("EmployeesApi.Models.YearSalary", b =>
                {
                    b.Property<int>("Year");

                    b.Property<int>("IdEmployee")
                        .HasColumnName("Id_Employee");

                    b.Property<int?>("Apr");

                    b.Property<int?>("Aug");

                    b.Property<int?>("Dec");

                    b.Property<int?>("Feb");

                    b.Property<int?>("Jan");

                    b.Property<int?>("Jul");

                    b.Property<int?>("Jun");

                    b.Property<int?>("Mar");

                    b.Property<int?>("May");

                    b.Property<int?>("Nov");

                    b.Property<int?>("Okt");

                    b.Property<int?>("Sep");

                    b.HasKey("Year", "IdEmployee");

                    b.HasIndex("IdEmployee");

                    b.ToTable("YearSalary");
                });

            modelBuilder.Entity("EmployeesApi.Models.YearSalary", b =>
                {
                    b.HasOne("EmployeesApi.Models.Employee", "IdEmployeeNavigation")
                        .WithMany("Salaries")
                        .HasForeignKey("IdEmployee")
                        .HasConstraintName("FK_YearSalary_ToEmployee");
                });
#pragma warning restore 612, 618
        }
    }
}
